### ISSUE TITLE
Rails Group Project Kanban Setup

### ISSUE THREAD

**Issue by Samuelwanza** [Al-Amin-Khan-Shakil/food-recipe#18]
@Al-Amin-Khan-Shakil  and @Samuelwanza  have conducted the following :
-We are a group of two
-We have created issues for the various tasks and gave points
-We then set up the KanBan board and populated the various issues as tasks.
-We then each other equal amount of tasks
Here is the repository link: https://github.com/users/Al-Amin-Khan-Shakil/projects/1

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi @Samuelwanza and @Al-Amin-Khan-Shakil,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] The project link you provided is invalid, Please add a valid repo link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @Samuelwanza and @Al-Amin-Khan-Shakil,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] There are no cards about the N+1 problem in your Kanban cards. 
As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Create%20tasks%20on%20your%20Kanban%20board%20based%20on%20the), Please add at least 1 card about the project requirement I mentioned.

![image](https://github.com/Al-Amin-Khan-Shakil/food-recipe/assets/68796232/a11daf5a-578d-4f06-8bbc-006867e64414)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Strangeal** [comment]
Hi @Samuelwanza, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjk5MjNhMmYyM2RjZmZmNWRkNjA3OWNmNGFhMjI4NDViOTg4N2UzNyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/x3l1BWfB85i2uU8nKK/giphy.gif)


## Highlights
- Added `N+1 problem` card ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
